# Generated by Django 2.2.7 on 2019-12-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensormanager', '0002_auto_20191213_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='invalid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
