# Generated by Django 2.2.7 on 2019-12-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensormanager', '0003_station_invalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='category',
            field=models.ManyToManyField(blank=True, to='sensormanager.Category'),
        ),
    ]
